FROM python:3.12-slim

WORKDIR /app

COPY requirements-docker.txt .

RUN pip install --no-cache-dir -r requirements-docker.txt

COPY kafka ./kafka
COPY backend ./backend
COPY database ./database
COPY config ./config
COPY model ./model
COPY data ./data

WORKDIR /app/kafka

CMD ["python", "consumer.py"]