FROM python:3.12-slim

WORKDIR /app

COPY requirements-docker.txt .

RUN pip install --no-cache-dir -r requirements-docker.txt

COPY kafka ./kafka
COPY data ./data

WORKDIR /app/kafka

CMD ["python", "producer.py"]